// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pond.proto

package pond

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Pond) Reset() {
	*x = Pond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pond) ProtoMessage() {}

func (x *Pond) ProtoReflect() protoreflect.Message {
	mi := &file_pond_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pond.ProtoReflect.Descriptor instead.
func (*Pond) Descriptor() ([]byte, []int) {
	return file_pond_proto_rawDescGZIP(), []int{0}
}

func (x *Pond) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Pond) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PondRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PondRequest) Reset() {
	*x = PondRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PondRequest) ProtoMessage() {}

func (x *PondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pond_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PondRequest.ProtoReflect.Descriptor instead.
func (*PondRequest) Descriptor() ([]byte, []int) {
	return file_pond_proto_rawDescGZIP(), []int{1}
}

func (x *PondRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PondResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Pond  `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *PondResponse) Reset() {
	*x = PondResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PondResponse) ProtoMessage() {}

func (x *PondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pond_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PondResponse.ProtoReflect.Descriptor instead.
func (*PondResponse) Descriptor() ([]byte, []int) {
	return file_pond_proto_rawDescGZIP(), []int{2}
}

func (x *PondResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PondResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PondResponse) GetData() *Pond {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pond_proto protoreflect.FileDescriptor

var file_pond_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f,
	0x6e, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x0b, 0x50, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x6e, 0x0a, 0x0c, 0x50, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x6f, 0x6e, 0x64, 0x2e, 0x50, 0x6f, 0x6e, 0x64, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x3e, 0x0a, 0x0b, 0x50, 0x6f, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x6f, 0x6e, 0x64,
	0x2e, 0x50, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70,
	0x6f, 0x6e, 0x64, 0x2e, 0x50, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6f, 0x6e, 0x64, 0x3b, 0x70, 0x6f, 0x6e, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pond_proto_rawDescOnce sync.Once
	file_pond_proto_rawDescData = file_pond_proto_rawDesc
)

func file_pond_proto_rawDescGZIP() []byte {
	file_pond_proto_rawDescOnce.Do(func() {
		file_pond_proto_rawDescData = protoimpl.X.CompressGZIP(file_pond_proto_rawDescData)
	})
	return file_pond_proto_rawDescData
}

var file_pond_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pond_proto_goTypes = []interface{}{
	(*Pond)(nil),         // 0: pond.Pond
	(*PondRequest)(nil),  // 1: pond.PondRequest
	(*PondResponse)(nil), // 2: pond.PondResponse
}
var file_pond_proto_depIdxs = []int32{
	0, // 0: pond.PondResponse.data:type_name -> pond.Pond
	1, // 1: pond.PondService.Pond:input_type -> pond.PondRequest
	2, // 2: pond.PondService.Pond:output_type -> pond.PondResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pond_proto_init() }
func file_pond_proto_init() {
	if File_pond_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pond_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pond_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PondRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pond_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PondResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pond_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pond_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pond_proto_goTypes,
		DependencyIndexes: file_pond_proto_depIdxs,
		MessageInfos:      file_pond_proto_msgTypes,
	}.Build()
	File_pond_proto = out.File
	file_pond_proto_rawDesc = nil
	file_pond_proto_goTypes = nil
	file_pond_proto_depIdxs = nil
}
