syntax = "proto3";

package feeder;

option go_package = "./proto/feeder;feeder";

message Feeder {
    string uuid = 1;
    string barcode = 2;
    string name = 3;
}
message FeederRequestAll {
}

message FeederRequestById {
    string id = 1;
}

message FeederRequestByBarcode {
    repeated string barcode = 1;
}

message FeederResponse {
    bool status = 1;
    string message = 2;
    optional Feeder data = 3;

}

message FeederResponses {
    bool status = 1;
    string message = 2;
    repeated Feeder data = 3;

}

service FeederService {
  rpc FetchFeeders(FeederRequestAll) returns (FeederResponses) {}
  rpc FindFeederById(FeederRequestById) returns (FeederResponse) {}
  rpc FindFeederByBarcode(FeederRequestByBarcode) returns (FeederResponses) {}
}
