// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: pond_feeders.proto

package pond_feeders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PondFeedersServiceClient is the client API for PondFeedersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PondFeedersServiceClient interface {
	FatchPondFeeders(ctx context.Context, in *PondFeedersRequest, opts ...grpc.CallOption) (*PondFeedersResponse, error)
}

type pondFeedersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPondFeedersServiceClient(cc grpc.ClientConnInterface) PondFeedersServiceClient {
	return &pondFeedersServiceClient{cc}
}

func (c *pondFeedersServiceClient) FatchPondFeeders(ctx context.Context, in *PondFeedersRequest, opts ...grpc.CallOption) (*PondFeedersResponse, error) {
	out := new(PondFeedersResponse)
	err := c.cc.Invoke(ctx, "/pond_feeders.PondFeedersService/FatchPondFeeders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PondFeedersServiceServer is the server API for PondFeedersService service.
// All implementations must embed UnimplementedPondFeedersServiceServer
// for forward compatibility
type PondFeedersServiceServer interface {
	FatchPondFeeders(context.Context, *PondFeedersRequest) (*PondFeedersResponse, error)
	mustEmbedUnimplementedPondFeedersServiceServer()
}

// UnimplementedPondFeedersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPondFeedersServiceServer struct {
}

func (UnimplementedPondFeedersServiceServer) FatchPondFeeders(context.Context, *PondFeedersRequest) (*PondFeedersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FatchPondFeeders not implemented")
}
func (UnimplementedPondFeedersServiceServer) mustEmbedUnimplementedPondFeedersServiceServer() {}

// UnsafePondFeedersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PondFeedersServiceServer will
// result in compilation errors.
type UnsafePondFeedersServiceServer interface {
	mustEmbedUnimplementedPondFeedersServiceServer()
}

func RegisterPondFeedersServiceServer(s grpc.ServiceRegistrar, srv PondFeedersServiceServer) {
	s.RegisterService(&PondFeedersService_ServiceDesc, srv)
}

func _PondFeedersService_FatchPondFeeders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PondFeedersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PondFeedersServiceServer).FatchPondFeeders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pond_feeders.PondFeedersService/FatchPondFeeders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PondFeedersServiceServer).FatchPondFeeders(ctx, req.(*PondFeedersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PondFeedersService_ServiceDesc is the grpc.ServiceDesc for PondFeedersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PondFeedersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pond_feeders.PondFeedersService",
	HandlerType: (*PondFeedersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FatchPondFeeders",
			Handler:    _PondFeedersService_FatchPondFeeders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pond_feeders.proto",
}
