// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pond_feeders.proto

package pond_feeders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PondFeeder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PondUuid   string `protobuf:"bytes,1,opt,name=pond_uuid,json=pondUuid,proto3" json:"pond_uuid,omitempty"`
	FeederUuid string `protobuf:"bytes,2,opt,name=feeder_uuid,json=feederUuid,proto3" json:"feeder_uuid,omitempty"`
	Barcode    string `protobuf:"bytes,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
}

func (x *PondFeeder) Reset() {
	*x = PondFeeder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_feeders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PondFeeder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PondFeeder) ProtoMessage() {}

func (x *PondFeeder) ProtoReflect() protoreflect.Message {
	mi := &file_pond_feeders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PondFeeder.ProtoReflect.Descriptor instead.
func (*PondFeeder) Descriptor() ([]byte, []int) {
	return file_pond_feeders_proto_rawDescGZIP(), []int{0}
}

func (x *PondFeeder) GetPondUuid() string {
	if x != nil {
		return x.PondUuid
	}
	return ""
}

func (x *PondFeeder) GetFeederUuid() string {
	if x != nil {
		return x.FeederUuid
	}
	return ""
}

func (x *PondFeeder) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type PondFeedersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PondUuid string `protobuf:"bytes,1,opt,name=pond_uuid,json=pondUuid,proto3" json:"pond_uuid,omitempty"`
}

func (x *PondFeedersRequest) Reset() {
	*x = PondFeedersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_feeders_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PondFeedersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PondFeedersRequest) ProtoMessage() {}

func (x *PondFeedersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pond_feeders_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PondFeedersRequest.ProtoReflect.Descriptor instead.
func (*PondFeedersRequest) Descriptor() ([]byte, []int) {
	return file_pond_feeders_proto_rawDescGZIP(), []int{1}
}

func (x *PondFeedersRequest) GetPondUuid() string {
	if x != nil {
		return x.PondUuid
	}
	return ""
}

type PondFeedersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*PondFeeder `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PondFeedersResponse) Reset() {
	*x = PondFeedersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pond_feeders_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PondFeedersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PondFeedersResponse) ProtoMessage() {}

func (x *PondFeedersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pond_feeders_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PondFeedersResponse.ProtoReflect.Descriptor instead.
func (*PondFeedersResponse) Descriptor() ([]byte, []int) {
	return file_pond_feeders_proto_rawDescGZIP(), []int{2}
}

func (x *PondFeedersResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PondFeedersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PondFeedersResponse) GetData() []*PondFeeder {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pond_feeders_proto protoreflect.FileDescriptor

var file_pond_feeders_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x64, 0x0a, 0x0a, 0x50, 0x6f, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6e, 0x64, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x31, 0x0a, 0x12, 0x50, 0x6f, 0x6e, 0x64,
	0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6f, 0x6e, 0x64, 0x55, 0x75, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x13, 0x50,
	0x6f, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x50, 0x6f, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x6f, 0x0a, 0x12, 0x50, 0x6f, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x46, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x6f, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x70,
	0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x6f, 0x6e, 0x64,
	0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x6f,
	0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x6f, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x3b, 0x70, 0x6f, 0x6e, 0x64,
	0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pond_feeders_proto_rawDescOnce sync.Once
	file_pond_feeders_proto_rawDescData = file_pond_feeders_proto_rawDesc
)

func file_pond_feeders_proto_rawDescGZIP() []byte {
	file_pond_feeders_proto_rawDescOnce.Do(func() {
		file_pond_feeders_proto_rawDescData = protoimpl.X.CompressGZIP(file_pond_feeders_proto_rawDescData)
	})
	return file_pond_feeders_proto_rawDescData
}

var file_pond_feeders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pond_feeders_proto_goTypes = []interface{}{
	(*PondFeeder)(nil),          // 0: pond_feeders.PondFeeder
	(*PondFeedersRequest)(nil),  // 1: pond_feeders.PondFeedersRequest
	(*PondFeedersResponse)(nil), // 2: pond_feeders.PondFeedersResponse
}
var file_pond_feeders_proto_depIdxs = []int32{
	0, // 0: pond_feeders.PondFeedersResponse.data:type_name -> pond_feeders.PondFeeder
	1, // 1: pond_feeders.PondFeedersService.FatchPondFeeders:input_type -> pond_feeders.PondFeedersRequest
	2, // 2: pond_feeders.PondFeedersService.FatchPondFeeders:output_type -> pond_feeders.PondFeedersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pond_feeders_proto_init() }
func file_pond_feeders_proto_init() {
	if File_pond_feeders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pond_feeders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PondFeeder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pond_feeders_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PondFeedersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pond_feeders_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PondFeedersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pond_feeders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pond_feeders_proto_goTypes,
		DependencyIndexes: file_pond_feeders_proto_depIdxs,
		MessageInfos:      file_pond_feeders_proto_msgTypes,
	}.Build()
	File_pond_feeders_proto = out.File
	file_pond_feeders_proto_rawDesc = nil
	file_pond_feeders_proto_goTypes = nil
	file_pond_feeders_proto_depIdxs = nil
}
