syntax = "proto3";

import "google/protobuf/timestamp.proto";

package pond;

option go_package = "server/grpc/pb/pond;pond";

message Pond {
    string uuid = 1;
    string name = 2;
    // google.protobuf.Timestamp created_at = 3;
    // google.protobuf.Timestamp updated_at = 4;
}

message PondRequest {
    string id = 1;
}

message PondResponse {
    bool status = 1;
    string message = 2;
    optional Pond data = 3;

}

service PondService {
  rpc Pond(PondRequest) returns (PondResponse) {}
}
