syntax = "proto3";

import "google/protobuf/timestamp.proto";

package pond_feeders;

option go_package = "server/grpc/pb/pond_feeders;pond_feeders";

message PondFeeder {
    string pond_uuid = 1;
    string feeder_uuid = 2;
    string name = 3;
    string barcode = 4;
}

message PondFeedersRequest {
    string pond_uuid = 1;
}

message PondFeedersResponse {
    bool status = 1;
    string message = 2;
    repeated PondFeeder data = 3;

}


service PondFeedersService {
  rpc FetchPondFeeders(PondFeedersRequest) returns (PondFeedersResponse) {}
}
