// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: feeder.proto

package feeder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeederServiceClient is the client API for FeederService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeederServiceClient interface {
	FetchFeeders(ctx context.Context, in *FeederRequestAll, opts ...grpc.CallOption) (*FeederResponses, error)
	FindFeederById(ctx context.Context, in *FeederRequestById, opts ...grpc.CallOption) (*FeederResponse, error)
	FindFeederByBarcode(ctx context.Context, in *FeederRequestByBarcode, opts ...grpc.CallOption) (*FeederResponses, error)
}

type feederServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeederServiceClient(cc grpc.ClientConnInterface) FeederServiceClient {
	return &feederServiceClient{cc}
}

func (c *feederServiceClient) FetchFeeders(ctx context.Context, in *FeederRequestAll, opts ...grpc.CallOption) (*FeederResponses, error) {
	out := new(FeederResponses)
	err := c.cc.Invoke(ctx, "/feeder.FeederService/FetchFeeders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feederServiceClient) FindFeederById(ctx context.Context, in *FeederRequestById, opts ...grpc.CallOption) (*FeederResponse, error) {
	out := new(FeederResponse)
	err := c.cc.Invoke(ctx, "/feeder.FeederService/FindFeederById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feederServiceClient) FindFeederByBarcode(ctx context.Context, in *FeederRequestByBarcode, opts ...grpc.CallOption) (*FeederResponses, error) {
	out := new(FeederResponses)
	err := c.cc.Invoke(ctx, "/feeder.FeederService/FindFeederByBarcode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeederServiceServer is the server API for FeederService service.
// All implementations must embed UnimplementedFeederServiceServer
// for forward compatibility
type FeederServiceServer interface {
	FetchFeeders(context.Context, *FeederRequestAll) (*FeederResponses, error)
	FindFeederById(context.Context, *FeederRequestById) (*FeederResponse, error)
	FindFeederByBarcode(context.Context, *FeederRequestByBarcode) (*FeederResponses, error)
	mustEmbedUnimplementedFeederServiceServer()
}

// UnimplementedFeederServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFeederServiceServer struct {
}

func (UnimplementedFeederServiceServer) FetchFeeders(context.Context, *FeederRequestAll) (*FeederResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchFeeders not implemented")
}
func (UnimplementedFeederServiceServer) FindFeederById(context.Context, *FeederRequestById) (*FeederResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindFeederById not implemented")
}
func (UnimplementedFeederServiceServer) FindFeederByBarcode(context.Context, *FeederRequestByBarcode) (*FeederResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindFeederByBarcode not implemented")
}
func (UnimplementedFeederServiceServer) mustEmbedUnimplementedFeederServiceServer() {}

// UnsafeFeederServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeederServiceServer will
// result in compilation errors.
type UnsafeFeederServiceServer interface {
	mustEmbedUnimplementedFeederServiceServer()
}

func RegisterFeederServiceServer(s grpc.ServiceRegistrar, srv FeederServiceServer) {
	s.RegisterService(&FeederService_ServiceDesc, srv)
}

func _FeederService_FetchFeeders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeederRequestAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeederServiceServer).FetchFeeders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeder.FeederService/FetchFeeders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeederServiceServer).FetchFeeders(ctx, req.(*FeederRequestAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeederService_FindFeederById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeederRequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeederServiceServer).FindFeederById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeder.FeederService/FindFeederById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeederServiceServer).FindFeederById(ctx, req.(*FeederRequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeederService_FindFeederByBarcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeederRequestByBarcode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeederServiceServer).FindFeederByBarcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeder.FeederService/FindFeederByBarcode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeederServiceServer).FindFeederByBarcode(ctx, req.(*FeederRequestByBarcode))
	}
	return interceptor(ctx, in, info, handler)
}

// FeederService_ServiceDesc is the grpc.ServiceDesc for FeederService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeederService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feeder.FeederService",
	HandlerType: (*FeederServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchFeeders",
			Handler:    _FeederService_FetchFeeders_Handler,
		},
		{
			MethodName: "FindFeederById",
			Handler:    _FeederService_FindFeederById_Handler,
		},
		{
			MethodName: "FindFeederByBarcode",
			Handler:    _FeederService_FindFeederByBarcode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeder.proto",
}
