// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: feeder.proto

package feeder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feeder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Barcode string `protobuf:"bytes,2,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Feeder) Reset() {
	*x = Feeder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feeder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feeder) ProtoMessage() {}

func (x *Feeder) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feeder.ProtoReflect.Descriptor instead.
func (*Feeder) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{0}
}

func (x *Feeder) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Feeder) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Feeder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FeederRequestAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FeederRequestAll) Reset() {
	*x = FeederRequestAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeederRequestAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederRequestAll) ProtoMessage() {}

func (x *FeederRequestAll) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederRequestAll.ProtoReflect.Descriptor instead.
func (*FeederRequestAll) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{1}
}

type FeederRequestById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FeederRequestById) Reset() {
	*x = FeederRequestById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeederRequestById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederRequestById) ProtoMessage() {}

func (x *FeederRequestById) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederRequestById.ProtoReflect.Descriptor instead.
func (*FeederRequestById) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{2}
}

func (x *FeederRequestById) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FeederRequestByBarcode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Barcode []string `protobuf:"bytes,1,rep,name=barcode,proto3" json:"barcode,omitempty"`
}

func (x *FeederRequestByBarcode) Reset() {
	*x = FeederRequestByBarcode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeederRequestByBarcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederRequestByBarcode) ProtoMessage() {}

func (x *FeederRequestByBarcode) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederRequestByBarcode.ProtoReflect.Descriptor instead.
func (*FeederRequestByBarcode) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{3}
}

func (x *FeederRequestByBarcode) GetBarcode() []string {
	if x != nil {
		return x.Barcode
	}
	return nil
}

type FeederResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Feeder `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *FeederResponse) Reset() {
	*x = FeederResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeederResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederResponse) ProtoMessage() {}

func (x *FeederResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederResponse.ProtoReflect.Descriptor instead.
func (*FeederResponse) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{4}
}

func (x *FeederResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FeederResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FeederResponse) GetData() *Feeder {
	if x != nil {
		return x.Data
	}
	return nil
}

type FeederResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*Feeder `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FeederResponses) Reset() {
	*x = FeederResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feeder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeederResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederResponses) ProtoMessage() {}

func (x *FeederResponses) ProtoReflect() protoreflect.Message {
	mi := &file_feeder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederResponses.ProtoReflect.Descriptor instead.
func (*FeederResponses) Descriptor() ([]byte, []int) {
	return file_feeder_proto_rawDescGZIP(), []int{5}
}

func (x *FeederResponses) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FeederResponses) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FeederResponses) GetData() []*Feeder {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_feeder_proto protoreflect.FileDescriptor

var file_feeder_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x06, 0x46, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x23, 0x0a, 0x11, 0x46, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x16,
	0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x42,
	0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x74, 0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x0f, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0xed, 0x01, 0x0a, 0x0d, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x43, 0x0a, 0x0c, 0x46, 0x61, 0x74, 0x63, 0x68, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x1a, 0x17, 0x2e, 0x66, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x13, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x42, 0x79, 0x42, 0x61, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x42, 0x61, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x1a, 0x17, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x1e, 0x5a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x3b, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feeder_proto_rawDescOnce sync.Once
	file_feeder_proto_rawDescData = file_feeder_proto_rawDesc
)

func file_feeder_proto_rawDescGZIP() []byte {
	file_feeder_proto_rawDescOnce.Do(func() {
		file_feeder_proto_rawDescData = protoimpl.X.CompressGZIP(file_feeder_proto_rawDescData)
	})
	return file_feeder_proto_rawDescData
}

var file_feeder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_feeder_proto_goTypes = []interface{}{
	(*Feeder)(nil),                 // 0: feeder.Feeder
	(*FeederRequestAll)(nil),       // 1: feeder.FeederRequestAll
	(*FeederRequestById)(nil),      // 2: feeder.FeederRequestById
	(*FeederRequestByBarcode)(nil), // 3: feeder.FeederRequestByBarcode
	(*FeederResponse)(nil),         // 4: feeder.FeederResponse
	(*FeederResponses)(nil),        // 5: feeder.FeederResponses
}
var file_feeder_proto_depIdxs = []int32{
	0, // 0: feeder.FeederResponse.data:type_name -> feeder.Feeder
	0, // 1: feeder.FeederResponses.data:type_name -> feeder.Feeder
	1, // 2: feeder.FeederService.FetchFeeders:input_type -> feeder.FeederRequestAll
	2, // 3: feeder.FeederService.FindFeederById:input_type -> feeder.FeederRequestById
	3, // 4: feeder.FeederService.FindFeederByBarcode:input_type -> feeder.FeederRequestByBarcode
	5, // 5: feeder.FeederService.FetchFeeders:output_type -> feeder.FeederResponses
	4, // 6: feeder.FeederService.FindFeederById:output_type -> feeder.FeederResponse
	5, // 7: feeder.FeederService.FindFeederByBarcode:output_type -> feeder.FeederResponses
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feeder_proto_init() }
func file_feeder_proto_init() {
	if File_feeder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feeder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feeder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feeder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeederRequestAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feeder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeederRequestById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feeder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeederRequestByBarcode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feeder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeederResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feeder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeederResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_feeder_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feeder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feeder_proto_goTypes,
		DependencyIndexes: file_feeder_proto_depIdxs,
		MessageInfos:      file_feeder_proto_msgTypes,
	}.Build()
	File_feeder_proto = out.File
	file_feeder_proto_rawDesc = nil
	file_feeder_proto_goTypes = nil
	file_feeder_proto_depIdxs = nil
}
